-- MySQL Script generated by MySQL Workbench
-- Wed May 27 23:38:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP TABLE IF EXISTS `GZZ_EST_REG` ;

CREATE TABLE IF NOT EXISTS `GZZ_EST_REG` (
  `EstRegCod` CHAR(1) NOT NULL,
  `EstRegDes` VARCHAR(40) NOT NULL,
  `EstRegEstReg` CHAR(1) NOT NULL,
  PRIMARY KEY (`EstRegCod`));

DROP TABLE IF EXISTS `GZZ_TIP_CLI` ;

CREATE TABLE IF NOT EXISTS `GZZ_TIP_CLI` (
  `TipCliCod` CHAR(2) NOT NULL,
  `TipCliDes` VARCHAR(40) NOT NULL,
  `TipCliEstReg` CHAR(1) NOT NULL,
  PRIMARY KEY (`TipCliCod`),
  INDEX `fk_tipcli_estreg` (`TipCliEstReg` ASC) VISIBLE,
  CONSTRAINT `fk_tipcli_estreg`
    FOREIGN KEY (`TipCliEstReg`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `GZZ_EST_CLI` ;

CREATE TABLE IF NOT EXISTS `GZZ_EST_CLI` (
  `EstCliCod` CHAR(1) NOT NULL,
  `EstCliDes` VARCHAR(40) NOT NULL,
  `EstCliEstReg` CHAR(1) NOT NULL,
  PRIMARY KEY (`EstCliCod`),
  INDEX `fk_estcli_estreg` (`EstCliEstReg` ASC) VISIBLE,
  CONSTRAINT `fk_estcli_estreg`
    FOREIGN KEY (`EstCliEstReg`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `GZZ_LIN_PRO` ;

CREATE TABLE IF NOT EXISTS `GZZ_LIN_PRO` (
  `LinProCod` SMALLINT NOT NULL,
  `LinProNom` VARCHAR(60) NOT NULL,
  `LinProTam` CHAR(1) NOT NULL,
  `LinProEstRegCod` CHAR(1) NOT NULL,
  PRIMARY KEY (`LinProCod`),
  INDEX `fk_linpro_estreg` (`LinProEstRegCod` ASC) VISIBLE,
  CONSTRAINT `fk_linpro_estreg`
    FOREIGN KEY (`LinProEstRegCod`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `GZZ_TIP_PRO` ;

CREATE TABLE IF NOT EXISTS `GZZ_TIP_PRO` (
  `TipProCod` SMALLINT NOT NULL,
  `TipProDes` VARCHAR(40) NOT NULL,
  `TipProTam` CHAR(1) NOT NULL,
  `TipProEstReg` CHAR(1) NOT NULL,
  PRIMARY KEY (`TipProCod`),
  INDEX `fk_tippro_estreg` (`TipProEstReg` ASC) VISIBLE,
  CONSTRAINT `fk_tippro_estreg`
    FOREIGN KEY (`TipProEstReg`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `GZZ_EST_PRO` ;

CREATE TABLE IF NOT EXISTS `GZZ_EST_PRO` (
  `EstProCod` CHAR(2) NOT NULL,
  `EstProDes` VARCHAR(40) NOT NULL,
  `EstProEstReg` CHAR(1) NOT NULL,
  PRIMARY KEY (`EstProCod`),
  INDEX `fk_estpro_estreg` (`EstProEstReg` ASC) VISIBLE,
  CONSTRAINT `fk_estpro_estreg`
    FOREIGN KEY (`EstProEstReg`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `GZZ_CAR_PER` ;

CREATE TABLE IF NOT EXISTS `GZZ_CAR_PER` (
  `CarPerCod` SMALLINT NOT NULL,
  `CarPerDes` VARCHAR(40) NOT NULL,
  `CarPerEstReg` CHAR(1) NOT NULL,
  PRIMARY KEY (`CarPerCod`),
  INDEX `fk_carper_estreg` (`CarPerEstReg` ASC) VISIBLE,
  CONSTRAINT `fk_carper_estreg`
    FOREIGN KEY (`CarPerEstReg`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `GZZ_CAR_PRO` ;

CREATE TABLE IF NOT EXISTS `GZZ_CAR_PRO` (
  `CarProCod` SMALLINT NOT NULL,
  `CarProDes` VARCHAR(40) NOT NULL,
  `CarProEstReg` CHAR(1) NOT NULL,
  PRIMARY KEY (`CarProCod`),
  INDEX `fk_carpro_estreg` (`CarProEstReg` ASC) VISIBLE,
  CONSTRAINT `fk_carpro_estreg`
    FOREIGN KEY (`CarProEstReg`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `GZZ_ETP_PRO` ;

CREATE TABLE IF NOT EXISTS `GZZ_ETP_PRO` (
  `EtpCod` SMALLINT NOT NULL,
  `EtpDes` VARCHAR(40) NOT NULL,
  `EtpTieEst` DECIMAL(5,2) NOT NULL,
  `EtpEstReg` CHAR(1) NOT NULL,
  PRIMARY KEY (`EtpCod`),
  INDEX `fk_etppro_estreg` (`EtpEstReg` ASC) VISIBLE,
  CONSTRAINT `fk_etppro_estreg`
    FOREIGN KEY (`EtpEstReg`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `G1M_CLIENTES` ;

CREATE TABLE IF NOT EXISTS `G1M_CLIENTES` (
  `CliCod` INT NOT NULL,
  `CliNom` VARCHAR(60) NOT NULL,
  `CliTipCod` CHAR(2) NOT NULL,
  `CliFecIng` DATE NULL DEFAULT NULL,
  `CliFecCes` DATE NULL DEFAULT NULL,
  `CliFecUltProCer` DATE NULL DEFAULT NULL,
  `CliEstCod` CHAR(1) NOT NULL,
  `CliEstRegCod` CHAR(1) NOT NULL,
  PRIMARY KEY (`CliCod`),
  INDEX `fk_cli_tipcli` (`CliTipCod` ASC) VISIBLE,
  INDEX `fk_cli_estcli` (`CliEstCod` ASC) VISIBLE,
  INDEX `fk_cli_estreg` (`CliEstRegCod` ASC) VISIBLE,
  CONSTRAINT `fk_cli_tipcli`
    FOREIGN KEY (`CliTipCod`)
    REFERENCES `GZZ_TIP_CLI` (`TipCliCod`),
  CONSTRAINT `fk_cli_estcli`
    FOREIGN KEY (`CliEstCod`)
    REFERENCES `GZZ_EST_CLI` (`EstCliCod`),
  CONSTRAINT `fk_cli_estreg`
    FOREIGN KEY (`CliEstRegCod`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `G1M_PERSONAL` ;

CREATE TABLE IF NOT EXISTS `G1M_PERSONAL` (
  `PerCod` INT NOT NULL,
  `PerNom` VARCHAR(60) NOT NULL,
  `PerCarCod` SMALLINT NOT NULL,
  `PerCosHor` DECIMAL(10,2) NOT NULL,
  `PerFecIng` DATE NOT NULL,
  `PerEstReg` CHAR(1) NOT NULL,
  PRIMARY KEY (`PerCod`),
  INDEX `fk_per_carper` (`PerCarCod` ASC) VISIBLE,
  INDEX `fk_per_estreg` (`PerEstReg` ASC) VISIBLE,
  CONSTRAINT `fk_per_carper`
    FOREIGN KEY (`PerCarCod`)
    REFERENCES `GZZ_CAR_PER` (`CarPerCod`),
  CONSTRAINT `fk_per_estreg`
    FOREIGN KEY (`PerEstReg`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `G1C_PER_CAR` ;

CREATE TABLE IF NOT EXISTS `G1C_PER_CAR` (
  `PerCod` INT NOT NULL,
  `CarProCod` SMALLINT NOT NULL,
  `PerCarProEstReg` CHAR(1) NOT NULL,
  PRIMARY KEY (`PerCod`, `CarProCod`),
  INDEX `fk_percar_carpro` (`CarProCod` ASC) VISIBLE,
  INDEX `fk_percar_estreg` (`PerCarProEstReg` ASC) VISIBLE,
  CONSTRAINT `fk_percar_per`
    FOREIGN KEY (`PerCod`)
    REFERENCES `G1M_PERSONAL` (`PerCod`),
  CONSTRAINT `fk_percar_carpro`
    FOREIGN KEY (`CarProCod`)
    REFERENCES `GZZ_CAR_PRO` (`CarProCod`),
  CONSTRAINT `fk_percar_estreg`
    FOREIGN KEY (`PerCarProEstReg`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `G1T_PRO_CAB` ;

CREATE TABLE IF NOT EXISTS `G1T_PRO_CAB` (
  `ProCliCod` INT NOT NULL,
  `ProTipCod` SMALLINT NOT NULL,
  `ProSec` SMALLINT NOT NULL,
  `ProFecCon` DATE NULL DEFAULT NULL,
  `ProFecPac` DATE NULL DEFAULT NULL,
  `ProFecIni` DATE NULL DEFAULT NULL,
  `ProFecEnt` DATE NULL DEFAULT NULL,
  `ProFecCer` DATE NULL DEFAULT NULL,
  `ProMonPre` DECIMAL(10,2) NULL DEFAULT NULL,
  `ProMonRea` DECIMAL(10,2) NULL DEFAULT NULL,
  `ProCosPre` DECIMAL(10,2) NULL DEFAULT NULL,
  `ProCosRea` DECIMAL(10,2) NULL DEFAULT NULL,
  `ProGasPre` DECIMAL(10,2) NULL DEFAULT NULL,
  `ProGasRea` DECIMAL(10,2) NULL DEFAULT NULL,
  `ProUtiPre` DECIMAL(10,2) NULL DEFAULT NULL,
  `ProUtiRea` DECIMAL(10,2) NULL DEFAULT NULL,
  `ProEstCod` CHAR(2) NOT NULL,
  `ProEstRegCod` CHAR(1) NOT NULL,
  PRIMARY KEY (`ProCliCod`, `ProTipCod`, `ProSec`),
  INDEX `fk_procab_tippro` (`ProTipCod` ASC) VISIBLE,
  INDEX `fk_procab_estpro` (`ProEstCod` ASC) VISIBLE,
  INDEX `fk_procab_estreg` (`ProEstRegCod` ASC) VISIBLE,
  CONSTRAINT `fk_procab_cli`
    FOREIGN KEY (`ProCliCod`)
    REFERENCES `G1M_CLIENTES` (`CliCod`),
  CONSTRAINT `fk_procab_tippro`
    FOREIGN KEY (`ProTipCod`)
    REFERENCES `GZZ_TIP_PRO` (`TipProCod`),
  CONSTRAINT `fk_procab_estpro`
    FOREIGN KEY (`ProEstCod`)
    REFERENCES `GZZ_EST_PRO` (`EstProCod`),
  CONSTRAINT `fk_procab_estreg`
    FOREIGN KEY (`ProEstRegCod`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `G1T_PRO_EQP` ;

CREATE TABLE IF NOT EXISTS `G1T_PRO_EQP` (
  `ProCliCod` INT NOT NULL,
  `ProTipCod` SMALLINT NOT NULL,
  `ProSec` SMALLINT NOT NULL,
  `PerCod` INT NOT NULL,
  `CarProCod` SMALLINT NOT NULL,
  `ProPerCarEstRegCod` CHAR(1) NOT NULL,
  PRIMARY KEY (`ProCliCod`, `ProTipCod`, `ProSec`, `PerCod`, `CarProCod`),
  INDEX `fk_proeqp_percar` (`PerCod` ASC, `CarProCod` ASC) VISIBLE,
  INDEX `fk_proeqp_estreg` (`ProPerCarEstRegCod` ASC) VISIBLE,
  CONSTRAINT `fk_proeqp_cab`
    FOREIGN KEY (`ProCliCod` , `ProTipCod` , `ProSec`)
    REFERENCES `G1T_PRO_CAB` (`ProCliCod` , `ProTipCod` , `ProSec`),
  CONSTRAINT `fk_proeqp_percar`
    FOREIGN KEY (`PerCod` , `CarProCod`)
    REFERENCES `G1C_PER_CAR` (`PerCod` , `CarProCod`),
  CONSTRAINT `fk_proeqp_estreg`
    FOREIGN KEY (`ProPerCarEstRegCod`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

DROP TABLE IF EXISTS `G1T_PRO_MOV` ;

CREATE TABLE IF NOT EXISTS `G1T_PRO_MOV` (
  `ProCliCod` INT NOT NULL,
  `ProTipCod` SMALLINT NOT NULL,
  `ProSec` SMALLINT NOT NULL,
  `PerCod` INT NOT NULL,
  `CarProCod` SMALLINT NOT NULL,
  `EtpCod` SMALLINT NOT NULL,
  `SecEtp` SMALLINT NOT NULL,
  `FecRegEtp` DATE NULL DEFAULT NULL,
  `HorTraEtp` SMALLINT NULL DEFAULT NULL,
  `MinTraEtp` SMALLINT NULL DEFAULT NULL,
  `EstRegCod` CHAR(1) NOT NULL,
  PRIMARY KEY (`ProCliCod`, `ProTipCod`, `ProSec`, `PerCod`, `CarProCod`, `EtpCod`, `SecEtp`),
  INDEX `fk_promov_etppro` (`EtpCod` ASC) VISIBLE,
  INDEX `fk_promov_estreg` (`EstRegCod` ASC) VISIBLE,
  CONSTRAINT `fk_promov_eqp`
    FOREIGN KEY (`ProCliCod` , `ProTipCod` , `ProSec` , `PerCod` , `CarProCod`)
    REFERENCES `G1T_PRO_EQP` (`ProCliCod` , `ProTipCod` , `ProSec` , `PerCod` , `CarProCod`),
  CONSTRAINT `fk_promov_etppro`
    FOREIGN KEY (`EtpCod`)
    REFERENCES `GZZ_ETP_PRO` (`EtpCod`),
  CONSTRAINT `fk_promov_estreg`
    FOREIGN KEY (`EstRegCod`)
    REFERENCES `GZZ_EST_REG` (`EstRegCod`));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;